### ISSUE TITLE
Can't share image on facebook messenger and instagram feed

### ISSUE THREAD

**Issue by Errechydy** [esysberlin/esys-flutter-share#66]
**Describe the bug**
I can't share image on facebook messenger and instagram feed

**To Reproduce**
- You can just try to share an image using either facebook messenger or instagram feed

**Desktop (please complete the following information):**
 - OS: Android

**Additional context**
- When i tried to share an image with facebook messenger i got this error:
```

E/DatabaseUtils( 5190): Writing exception to parcel
E/DatabaseUtils( 5190): java.lang.SecurityException: Permission Denial: reading de.esys.esysfluttershare.EsysFlutterShareFileProvider uri content://com.example.testapp.fileprovider.github.com%2Forgs%2Fesysberlin%2Fesys-flutter-share/files/esys.png from pid=1870, uid=1000 requires the provider be exported, or grantUriPermission()
E/DatabaseUtils( 5190): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:653)
E/DatabaseUtils( 5190): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:497)
E/DatabaseUtils( 5190): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:212)
E/DatabaseUtils( 5190): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
E/DatabaseUtils( 5190): 	at android.os.Binder.execTransact(Binder.java:582)
```

**Comment by FilipeOS** [comment]
Same issue here

**Comment by fabioselau077** [comment]
Same here

**Comment by xlr8max** [comment]
Same here works fine with Whatsapp but I don't have other options like messenger,instagram,snapchat,etc. I have attached a picture
[https://ibb.co/G5M3jKZ](url)
