### ISSUE TITLE
MissingPluginException(No implementation found for method shareImage on channel channel:github.com/orgs/esysberlin/esys-flutter-share

### ISSUE THREAD

**Issue by Livinglist** [esysberlin/esys-flutter-share#9]
`E/flutter (28780): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (28780): MissingPluginException(No implementation found for method shareImage on channel channel:github.com/orgs/esysberlin/esys-flutter-share)
E/flutter (28780): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
E/flutter (28780): <asynchronous suspension>
E/flutter (28780): #1      EsysFlutterShare.shareImage (package:esys_flutter_share/esys_flutter_share.dart:34:14)
E/flutter (28780): <asynchronous suspension>
E/flutter (28780): #2      RoutineDetailPageState._shareImage (package:WorkoutPlanner/routineDetailPage.dart:199:30)
E/flutter (28780): <asynchronous suspension>
E/flutter (28780): #3      RoutineDetailPageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:WorkoutPlanner/routineDetailPage.dart:95:60)
E/flutter (28780): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter (28780): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter (28780): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (28780): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (28780): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (28780): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (28780): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (28780): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (28780): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
E/flutter (28780): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter (28780): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter (28780): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (28780): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (28780): #17     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter (28780): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)`

**Comment by d-wolf** [comment]
I need more information to solve the problem. Can you please explain what led you to the problem? Could you provide your source code?

**Comment by luistheone** [comment]
Have the same problem.
I also copied the example file and got the same problem.
it works in IOS but not in android.

**Comment by menqi20** [comment]
Have the same problem

**Comment by kelegorm** [comment]
It's often happens when you try hot reload. Native parts of flutter app (and from dependencies) are not adding at hot reload. Need to stop and run app again. Tell if bug happens after that

**Comment by rgarcia11** [comment]
I had the same issue as soon as I installed the library. Uninstalling the app and launching it again did the trick! I hope it works if someone finds this as I did. Thanks @kelegorm.

**Comment by JAICHANGPARK** [comment]
I had Same problem 

```
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): Failed to handle method call
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:605)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at de.esys.esysfluttershare.EsysFlutterSharePlugin.file(EsysFlutterSharePlugin.java:82)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at de.esys.esysfluttershare.EsysFlutterSharePlugin.onMethodCall(EsysFlutterSharePlugin.java:46)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at android.app.ActivityThread.main(ActivityThread.java:7045)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#channel:github.com/orgs/esysberlin/esys-flutter-share(10700): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/flutter (10700): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference, null)
```

**Comment by rmena28** [comment]
I have the same issue that @JAICHANGPARK mentions.

**Comment by Faiyyaz** [comment]
Even for me the same issue is occurring what @JAICHANGPARK had mentioned.

Please help

**Comment by rmena28** [comment]
> Even for me the same issue is occurring what @JAICHANGPARK had mentioned.
> 
> Please help

I was able to fix this issue by running "flutter clean" in my project folder.
